/* MoneyMap investments module.
   Extracted from v0.10.0-alpha app.js with behavior-preserving function moves. */

function includedHoldings(){ return (state.holdings||[]).filter(h=>h.includeNetWorth!==false); }

function holdingValue(h){ return nval(h.quantity)*nval(h.price); }

function holdingCost(h){ return nval(h.quantity)*nval(h.costBasis); }

function renderInvestments(){
  const metrics=document.getElementById('investmentMetrics'); if(!metrics) return;
  const holdings=state.holdings||[]; const value=holdings.reduce((a,h)=>a+holdingValue(h),0); const cost=holdings.reduce((a,h)=>a+holdingCost(h),0); const gain=value-cost; const inc=includedHoldings().reduce((a,h)=>a+holdingValue(h),0);
  metrics.innerHTML=`<div class="tracker-stat"><div class="metric-label">Market value</div><div class="metric-value good">${money(value)}</div><div class="metric-sub">${holdings.length} holding${holdings.length===1?'':'s'} tracked manually</div></div><div class="tracker-stat"><div class="metric-label">Cost basis</div><div class="metric-value blue">${money(cost)}</div><div class="metric-sub">Manual cost basis</div></div><div class="tracker-stat"><div class="metric-label">Unrealized gain/loss</div><div class="metric-value ${gain>=0?'good':'bad'}">${money(gain)}</div><div class="metric-sub">${cost?pctFmt((gain/cost)*100):'No cost basis yet'}</div></div><div class="tracker-stat"><div class="metric-label">Included in net worth</div><div class="metric-value purple">${money(inc)}</div><div class="metric-sub">Exclude duplicates with account balances</div></div>`;
  const rows=document.getElementById('holdingRows');
  if(rows){ rows.innerHTML=holdings.length?holdings.map(h=>{ const value=holdingValue(h); const cost=holdingCost(h); const gain=value-cost; return `<tr><td><b>${escapeHtml(h.symbol||h.name||'Holding')}</b><br><span class="muted">${escapeHtml(h.name||'Manual holding')} · <span class="balance-badge ${h.includeNetWorth!==false?'include':'exclude'}">${h.includeNetWorth!==false?'Included':'Excluded'}</span></span></td><td>${escapeHtml(h.account||'Manual')}</td><td>${escapeHtml(h.assetClass||'Stock')}</td><td class="amount-cell">${nval(h.quantity).toLocaleString()}</td><td class="amount-cell">${money(h.price,{cents:true})}</td><td class="amount-cell good">${money(value)}</td><td class="amount-cell ${gain>=0?'good':'bad'}">${money(gain)}</td><td class="right"><div class="table-actions"><button class="btn btn-small" onclick="toggleHoldingInclude('${h.id}')">${h.includeNetWorth!==false?'Exclude':'Include'}</button><button class="btn btn-small" onclick="openDrawer('holding', findById('holdings','${h.id}'))">Edit</button><button class="btn btn-small btn-danger" onclick="deleteTrackerItem('holdings','${h.id}')">Delete</button></div></td></tr>`; }).join(''):`<tr><td colspan="8"><div class="empty" style="min-height:150px"><div><strong>No holdings yet.</strong><p>Add stocks, funds, crypto, bonds, or cash positions manually.</p><button class="btn btn-primary" onclick="openDrawer('holding')">Add holding</button></div></div></td></tr>`; }
  const alloc=allocationRows(); const list=document.getElementById('allocationList'); if(list){ list.innerHTML=alloc.length?alloc.map((a,i)=>`<div class="mini-item"><div><b><span class="dot" style="background:${COLORS[i%COLORS.length]}"></span> ${escapeHtml(a.name)}</b><br><span>${pctFmt(a.pct)} of portfolio</span><div class="allocation-bar"><span style="width:${a.pct}%;background:${COLORS[i%COLORS.length]}"></span></div></div><strong>${money(a.value)}</strong></div>`).join(''):emptyMini('No allocation yet','Add holdings to see asset class weights.','Add holding','openDrawer(\'holding\')'); }
  const notes=document.getElementById('investmentNotes'); if(notes){ notes.innerHTML=`<div class="mini-item"><div><b>Double-count guard</b><br><span>Exclude holdings from net worth if the same portfolio is already an included manual account balance.</span></div><span>Important</span></div><div class="mini-item"><div><b>Manual pricing</b><br><span>Prices do not update automatically. Edit holdings after you check current values.</span></div><span>Private</span></div>`; }
}

function allocationRows(){ const total=(state.holdings||[]).reduce((a,h)=>a+holdingValue(h),0); const map={}; (state.holdings||[]).forEach(h=>{ const k=h.assetClass||'Other'; map[k]=(map[k]||0)+holdingValue(h); }); return Object.entries(map).filter(([,v])=>v>0).sort((a,b)=>b[1]-a[1]).map(([name,value])=>({name,value,pct:total?value/total*100:0})); }

function toggleHoldingInclude(id){ const h=(state.holdings||[]).find(x=>x.id===id); if(!h) return; h.includeNetWorth=h.includeNetWorth===false; renderAll(); toast(h.includeNetWorth?'Holding included in net worth.':'Holding excluded from net worth.'); }

function saveHolding(id){ const payload={symbol:document.getElementById('holdSymbol').value.trim().toUpperCase(), name:document.getElementById('holdName').value.trim(), account:document.getElementById('holdAccount').value.trim(), assetClass:document.getElementById('holdClass').value.trim()||'Stock', quantity:nval(document.getElementById('holdQty').value), price:nval(document.getElementById('holdPrice').value), costBasis:nval(document.getElementById('holdCost').value), includeNetWorth:document.getElementById('holdInclude').classList.contains('on'), notes:document.getElementById('holdNotes').value.trim()}; if(!payload.symbol && !payload.name){ toast('Symbol or holding name required.'); return; } if(!payload.quantity || !payload.price){ toast('Quantity and price required.'); return; } state.holdings=state.holdings||[]; const item=id?state.holdings.find(x=>x.id===id):null; if(item) Object.assign(item,payload); else state.holdings.push({id:uid('hold'),createdAt:new Date().toISOString(),...payload}); closeDrawer(); toast('Holding saved.'); renderAll(); }
